export const companies = {
  care_health: {
    id: 1,
    name: "Care Health Insurance",
    short_name: "Care Health",
    alias: "care_health",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/care_health_insurance_logo.png",
    insurance_types: [
      "health",
      "top_up",
      "personal_accident",
      "critical_illness",
      "cancer",
    ],
    csr: 92.4,
  },
  star: {
    id: 2,
    name: "Star Health & Allied Insurance",
    short_name: "Star Health",
    alias: "star",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/STAR%20HEALTH%20LOGO%20%2810%29.png",
    insurance_types: ["health", "top_up"],
    csr: 78.59,
  },
  aditya_birla: {
    id: 3,
    name: "Aditya Birla Health Insurance",
    short_name: "Aditya Birla Health",
    alias: "aditya_birla",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Aditya_logo%20-%20Copy.png",
    insurance_types: [
      "personal_accident",
      "critical_illness",
      "cancer",
      "health",
      "top_up",
    ],
    csr: 76.15,
  },
  icici_lombard: {
    id: 4,
    name: "ICICI Lombard General Insurance",
    short_name: "ICICI Lombard",
    alias: "icici_lombard",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/icici_lombard.png",
    insurance_types: ["health", "top_up"],
    csr: 82.06,
  },
  max_bupa: {
    id: 5,
    name: "Niva Bupa Health Insurance",
    short_name: "Niva Bupa",
    alias: "max_bupa",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/niva.png",
    insurance_types: ["health", "top_up"],
    csr: 87.08,
  },
  tata_aig: {
    id: 6,
    name: "Tata AIG General Insurance",
    short_name: "TATA AIG",
    alias: "tata_aig",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/TATA%20AIG.png",
    insurance_types: ["health", "top_up", "personal_accident"],
    csr: 94,
  },
  hdfc_ergo: {
    id: 7,
    name: "HDFC ERGO Health Insurance",
    short_name: "HDFC ERGO",
    alias: "hdfc_ergo",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/hdfc.png",
    insurance_types: ["health", "top_up"],
    csr: 89.32,
  },
  go_digit: {
    id: 10,
    name: "Go Digit General Insurance",
    short_name: "Go Digit",
    alias: "go_digit",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/digit.png",
    insurance_types: ["health"],
    csr: 91.72,
  },
  manipal_cigna: {
    id: 11,
    name: "Manipal Cigna Health Insurance",
    short_name: "Manipal Cigna Health",
    alias: "manipal_cigna",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/manipal.png",
    insurance_types: ["health", "top_up"],
    csr: 86.67,
  },
  universal_sompo: {
    id: 12,
    name: "Universal Sompo General Insurance",
    short_name: "Universal Sompo",
    alias: "universal_sompo",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/sompo%20new%20logo.png",
    insurance_types: ["health", "top_up"],
    csr: 88.94,
  },
  icici_pru: {
    id: 13,
    name: "ICICI Prudential Life Insurance Company Limited",
    short_name: "ICICI Prudential Life",
    alias: "icici_pru",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/ICICI%20Life.png",
    insurance_types: ["term"],
    csr: 97.9,
  },
  max_life: {
    id: 14,
    name: "Max Life Insurance Company Limited",
    short_name: "Max Life Insurance",
    alias: "max_life",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Max-Life.png",
    insurance_types: ["term"],
    csr: 99.35,
  },
  hdfc_life: {
    id: 15,
    name: "HDFC Life Insurance Company Limited",
    short_name: "HDFC Life",
    alias: "hdfc_life",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/HDFC-Life.png",
    insurance_types: ["term"],
    csr: 98.01,
  },
  kotak_life: {
    id: 16,
    name: "Kotak Mahindra Life Insurance Company Limited",
    short_name: "Kotak Mahindra Life",
    alias: "kotak_life",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Kotak-Life.png",
    insurance_types: ["term"],
    csr: 98.5,
  },
  tata_aia: {
    id: 17,
    name: "TATA AIA Life Insurance Company Limited",
    short_name: "Tata AIA Life",
    alias: "tata_aia",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Tata-AIA-Life.png",
    insurance_types: ["term"],
    csr: 98.02,
  },
  bajaj_life: {
    id: 18,
    name: "Bajaj Allianz Life Insurance Company Limited",
    short_name: "Bajaj Allianz Life",
    alias: "bajaj_life",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Bajaj-Allainz-Life.png",
    insurance_types: ["term"],
    csr: 98.02,
  },
  aegon_life: {
    id: 19,
    name: "Aegon Life Insurance Company Limited",
    short_name: "Aegon Life",
    alias: "aegon_life",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Aegon-Life.png",
    insurance_types: ["term"],
    csr: 98.01,
  },
  pnb_metlife: {
    id: 20,
    name: "PNB MetLife India Insurance Company Limited",
    short_name: "PNB Metlife",
    alias: "pnb_metlife",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/PNB-Metlite.png",
    insurance_types: ["term"],
    csr: 97.18,
  },
  edelweiss_tokio_life: {
    id: 21,
    name: "Edelweiss Tokio Life Insurance Company Limited",
    short_name: "Edelweiss Tokio Life",
    alias: "edelweiss_tokio_life",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/edelweiss%20%281%29.png",
    insurance_types: ["term"],
    csr: 83.38,
  },
  bharti_axa_life: {
    id: 23,
    name: "Bharti AXA Life Insurance Company Limited",
    short_name: "Bharti AXA Life",
    alias: "bharti_axa_life",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/new%20axa.jpg",
    insurance_types: ["term"],
    csr: 97.35,
  },
  royal_sundaram: {
    id: 24,
    name: "Royal Sundaram General Insurance",
    short_name: "Royal Sundaram",
    alias: "royal_sundaram",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/royal-sundaram-logo-1F492A3E2A-seeklogo.com.png",
    insurance_types: ["health"],
    csr: 92.35,
  },
  birla_sun_life: {
    id: 26,
    name: "Aditya Birla Sun Life Insurance Company Ltd.",
    short_name: "Birla Sun Life",
    alias: "birla_sun_life",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/1391_Birla-Sun-Life%20%281%29.jpg",
    insurance_types: ["term"],
    csr: 97.54,
  },
  indiafirst_life: {
    id: 27,
    name: "IndiaFirst Life Insurance Company Limited",
    short_name: "IndiaFirst Life",
    alias: "indiafirst_life",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/India-First-Life.png",
    insurance_types: ["term"],
    csr: 96.81,
  },
  sbi_general: {
    id: 31,
    name: "SBI General Insurance",
    short_name: "SBI General",
    alias: "sbi_general",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Capture.PNG",
    insurance_types: ["health", "top_up"],
    csr: 91.55,
  },
  reliance_general: {
    id: 38,
    name: "Reliance General Insurance",
    short_name: "Reliance General",
    alias: "reliance_general",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Reliance%20logo.png",
    insurance_types: ["health"],
    csr: 93.48,
  },
  future_generali: {
    id: 39,
    name: "Future Generali India Insurance Company",
    short_name: "Future Generali",
    alias: "future_generali",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/FG%20logo.png",
    insurance_types: ["health"],
    csr: 91,
  },
  national_insurance: {
    id: 40,
    name: "National Insurance Company Limited",
    short_name: "National Insurance",
    alias: "national_insurance",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/nic%20logo.png",
    insurance_types: ["health", "top_up"],
    csr: 90.38,
  },
  new_india_assurance: {
    id: 41,
    name: "The New India Assurance Co. Ltd.",
    short_name: "New India Assurance",
    alias: "new_india_assurance",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/new_india_logo.png",
    insurance_types: ["health", "top_up"],
    csr: 99.07,
  },
  bajaj_allianz: {
    id: 42,
    name: "Bajaj Allianz General Insurance",
    short_name: "Bajaj Allianz",
    alias: "bajaj_allianz",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Bajaj%20Logo%20%281%29.jpeg",
    insurance_types: ["health", "pet"],
    csr: 93.59,
  },
  united_india: {
    id: 46,
    name: "United India Insurance",
    short_name: "United India",
    alias: "united_india",
    logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/",
    insurance_types: ["health"],
    csr: 93.96,
  },
};
