import { members } from "./members";
import { deductibles } from "./deductibles";

const config = {
  genders: [
    { code: "M", display_name: "Male" },
    { code: "F", display_name: "Female" },
  ],
  plantypes: [
    { code: "I", display_name: "Individual", description: "" },
    {
      code: "F",
      display_name: "Family Floater",
      description:
        "Family floater plan covers your entire family under one single plan. The total sum insured is shared amongst each family members",
    },
    {
      code: "M",
      display_name: "Multi Individual",
      description:
        "Multi-individual plan covers each family member under separate sum insured. You get discount if you cover 2 or more family members under multi-individual plan.",
    },
  ],
  members,
  popularcities: [
    { name: "Delhi", pincode: 110001 },
    { name: "Pune", pincode: 410301 },
    { name: "Bengaluru", pincode: 560001 },
    { name: "Mumbai", pincode: 400002 },
    { name: "Gurgaon", pincode: 122001 },
    { name: "Ahmedabad", pincode: 380001 },
    { name: "Thane", pincode: 400601 },
  ],
  existingdiseases: [
    { code: "diabetes", display_name: "Diabetes" },
    { code: "hypertension", display_name: "Hypertension" },
    { code: "heart_disease", display_name: "Heart Disease" },
    { code: "other_diseases", display_name: "Other Diseases" },
  ],
  companies: {
    care_health: {
      id: 1,
      name: "Care Health Insurance",
      short_name: "Care Health",
      alias: "care_health",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/care_health_insurance_logo.png",
      insurance_types: [
        "health",
        "top_up",
        "personal_accident",
        "critical_illness",
        "cancer",
      ],
      csr: 92.4,
    },
    star: {
      id: 2,
      name: "Star Health & Allied Insurance",
      short_name: "Star Health",
      alias: "star",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/STAR%20HEALTH%20LOGO%20%2810%29.png",
      insurance_types: ["health", "top_up"],
      csr: 78.59,
    },
    aditya_birla: {
      id: 3,
      name: "Aditya Birla Health Insurance",
      short_name: "Aditya Birla Health",
      alias: "aditya_birla",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Aditya_logo%20-%20Copy.png",
      insurance_types: [
        "personal_accident",
        "critical_illness",
        "cancer",
        "health",
        "top_up",
      ],
      csr: 76.15,
    },
    icici_lombard: {
      id: 4,
      name: "ICICI Lombard General Insurance",
      short_name: "ICICI Lombard",
      alias: "icici_lombard",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/icici_lombard.png",
      insurance_types: ["health", "top_up"],
      csr: 82.06,
    },
    max_bupa: {
      id: 5,
      name: "Niva Bupa Health Insurance",
      short_name: "Niva Bupa",
      alias: "max_bupa",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/niva.png",
      insurance_types: ["health", "top_up"],
      csr: 87.08,
    },
    tata_aig: {
      id: 6,
      name: "Tata AIG General Insurance",
      short_name: "TATA AIG",
      alias: "tata_aig",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/TATA%20AIG.png",
      insurance_types: ["health", "top_up", "personal_accident"],
      csr: 94,
    },
    hdfc_ergo: {
      id: 7,
      name: "HDFC ERGO Health Insurance",
      short_name: "HDFC ERGO",
      alias: "hdfc_ergo",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/hdfc.png",
      insurance_types: ["health", "top_up"],
      csr: 89.32,
    },
    go_digit: {
      id: 10,
      name: "Go Digit General Insurance",
      short_name: "Go Digit",
      alias: "go_digit",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/digit.png",
      insurance_types: ["health"],
      csr: 91.72,
    },
    manipal_cigna: {
      id: 11,
      name: "Manipal Cigna Health Insurance",
      short_name: "Manipal Cigna Health",
      alias: "manipal_cigna",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/manipal.png",
      insurance_types: ["health", "top_up"],
      csr: 86.67,
    },
    icici_pru: {
      id: 13,
      name: "ICICI Prudential Life Insurance Company Limited",
      short_name: "ICICI Prudential Life",
      alias: "icici_pru",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/ICICI%20Life.png",
      insurance_types: ["term"],
      csr: 97.9,
    },
    max_life: {
      id: 14,
      name: "Max Life Insurance Company Limited",
      short_name: "Max Life Insurance",
      alias: "max_life",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Max-Life.png",
      insurance_types: ["term"],
      csr: 99.35,
    },
    hdfc_life: {
      id: 15,
      name: "HDFC Life Insurance Company Limited",
      short_name: "HDFC Life",
      alias: "hdfc_life",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/HDFC-Life.png",
      insurance_types: ["term"],
      csr: 98.01,
    },
    kotak_life: {
      id: 16,
      name: "Kotak Mahindra Life Insurance Company Limited",
      short_name: "Kotak Mahindra Life",
      alias: "kotak_life",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Kotak-Life.png",
      insurance_types: ["term"],
      csr: 98.5,
    },
    tata_aia: {
      id: 17,
      name: "TATA AIA Life Insurance Company Limited",
      short_name: "Tata AIA Life",
      alias: "tata_aia",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Tata-AIA-Life.png",
      insurance_types: ["term"],
      csr: 98.02,
    },
    bajaj_life: {
      id: 18,
      name: "Bajaj Allianz Life Insurance Company Limited",
      short_name: "Bajaj Allianz Life",
      alias: "bajaj_life",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Bajaj-Allainz-Life.png",
      insurance_types: ["term"],
      csr: 98.02,
    },
    aegon_life: {
      id: 19,
      name: "Aegon Life Insurance Company Limited",
      short_name: "Aegon Life",
      alias: "aegon_life",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Aegon-Life.png",
      insurance_types: ["term"],
      csr: 98.01,
    },
    pnb_metlife: {
      id: 20,
      name: "PNB MetLife India Insurance Company Limited",
      short_name: "PNB Metlife",
      alias: "pnb_metlife",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/PNB-Metlite.png",
      insurance_types: ["term"],
      csr: 97.18,
    },
    edelweiss_tokio_life: {
      id: 21,
      name: "Edelweiss Tokio Life Insurance Company Limited",
      short_name: "Edelweiss Tokio Life",
      alias: "edelweiss_tokio_life",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/edelweiss%20%281%29.png",
      insurance_types: ["term"],
      csr: 83.38,
    },
    bharti_axa_life: {
      id: 23,
      name: "Bharti AXA Life Insurance Company Limited",
      short_name: "Bharti AXA Life",
      alias: "bharti_axa_life",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/new%20axa.jpg",
      insurance_types: ["term"],
      csr: 97.35,
    },
    royal_sundaram: {
      id: 24,
      name: "Royal Sundaram General Insurance",
      short_name: "Royal Sundaram",
      alias: "royal_sundaram",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/royal-sundaram-logo-1F492A3E2A-seeklogo.com.png",
      insurance_types: ["health"],
      csr: 92.35,
    },
    birla_sun_life: {
      id: 26,
      name: "Aditya Birla Sun Life Insurance Company Ltd.",
      short_name: "Birla Sun Life",
      alias: "birla_sun_life",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/1391_Birla-Sun-Life%20%281%29.jpg",
      insurance_types: ["term"],
      csr: 97.54,
    },
    indiafirst_life: {
      id: 27,
      name: "IndiaFirst Life Insurance Company Limited",
      short_name: "IndiaFirst Life",
      alias: "indiafirst_life",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/India-First-Life.png",
      insurance_types: ["term"],
      csr: 96.81,
    },
    sbi_general: {
      id: 31,
      name: "SBI General Insurance",
      short_name: "SBI General",
      alias: "sbi_general",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Capture.PNG",
      insurance_types: ["health", "top_up"],
      csr: 91.55,
    },
    national_insurance: {
      id: 40,
      name: "National Insurance Company Limited",
      short_name: "National Insurance",
      alias: "national_insurance",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/nic%20logo.png",
      insurance_types: ["health", "top_up"],
      csr: 90.38,
    },
    new_india_assurance: {
      id: 41,
      name: "The New India Assurance Co. Ltd.",
      short_name: "New India Assurance",
      alias: "new_india_assurance",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/new_india_logo.png",
      insurance_types: ["health", "top_up"],
      csr: 99.07,
    },
    bajaj_allianz: {
      id: 42,
      name: "Bajaj Allianz General Insurance",
      short_name: "Bajaj Allianz",
      alias: "bajaj_allianz",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/Bajaj%20Logo%20%281%29.jpeg",
      insurance_types: ["health", "pet"],
      csr: 93.59,
    },
    united_india: {
      id: 46,
      name: "United India Insurance",
      short_name: "United India",
      alias: "united_india",
      logo: "https://health-admin-bucket.s3.ap-south-1.amazonaws.com/Company_logo/",
      insurance_types: ["health"],
      csr: 93.96,
    },
  },
  premiums: [
    { code: "<5000", display_name: "< \u20b95,000" },
    { code: "5000-10000", display_name: "\u20b95,000 - \u20b910,000" },
    { code: "10000-15000", display_name: "\u20b910,000 - \u20b915,000" },
    { code: "15000-20000", display_name: "\u20b915,000 - \u20b920,000" },
    { code: ">20000", display_name: "> \u20b920,000" },
  ],
  covers: [
    { code: "100000-300000", display_name: "1 to 3 Lacs" },
    { code: "300000-500000", display_name: "3 to 5 Lacs" },
    { code: "500000-1000000", display_name: "5 to 10 Lacs" },
    { code: "1000000-1500000", display_name: "10 to 15 Lacs" },
    { code: "1500000-2500000", display_name: "15 to 25 Lacs" },
    { code: "2500001-100000000", display_name: "More than 25 Lacs" },
  ],
  morefilters: [
    {
      group_name: "Popular Filters",
      code: "popular_filters",
      type: "checkbox",
      options: [
        {
          code: "room_rent_charges",
          display_name: "No Room rent limit",
          description:
            "Room Rent means the amount charged by a Hospital towards Room and Boarding expenses and shall include the associated medical expenses\n                        ",
          operator: "equals",
          value_to_compare: "No sub-limit",
          visible_on_sections: ["health", "top_up"],
        },
        {
          code: "co_payment",
          display_name: "No Copay",
          description:
            "Co-payment means a cost sharing requirement that the Policy holder will bear a specified percentage of the admissible claims amount\n                        ",
          operator: "equals",
          value_to_compare: "No",
          visible_on_sections: ["health", "top_up"],
        },
        {
          code: "single_private_room",
          display_name: "Single Private Room",
          description:
            "Single Private Room means a basic (most economical of all accommodation) category of single room in a Hospital with or without air-conditioning facility where a single patient is accommodated and which has an attached toilet.\n                        ",
          operator: "in_array",
          value_to_compare: [
            "Single Private Room",
            "Single Private Room upgradable",
            "Single Private A/C Room",
            "Single Private A/C Room (Upgradable)",
          ],
          visible_on_sections: ["health", "top_up"],
        },
        {
          code: "no_pre_policy_check_up",
          display_name: "No Pre-policy Check up",
          description:
            "The pre-policy medical checkup refers to the medical examination that is required before issuing the policy.\n                        ",
          visible_on_sections: ["health", "top_up"],
        },
      ],
    },
    {
      group_name: "Pre existing Ailments",
      code: "pre_existing_ailments",
      type: "radio",
      options: [
        {
          code: "pre_existing_disease_cover_1",
          display_name: "Covered after 1 year",
          description:
            "Pre-Existing ailment means any condition, injury or disease that is diagnosed or for which medical advice or treatment was recommended by, or received from, a physician prior to the effective date of the policy or its reinstatement. Medical Expesnes are covered after a waiting period of 1 year.\n                        ",
          operator: "equals",
          value_to_compare: "1 Year",
          visible_on_sections: ["health", "top_up"],
        },
        {
          code: "pre_existing_disease_cover_2",
          display_name: "Covered after 2 years",
          description:
            "Pre-Existing ailment means any condition, injury or disease that is diagnosed or for which medical advice or treatment was recommended by, or received from, a physician prior to the effective date of the policy or its reinstatement. Medical Expesnes are covered after a waiting period of 2 years.\n                        ",
          operator: "equals",
          value_to_compare: "2 Years",
          visible_on_sections: ["health", "top_up"],
        },
        {
          code: "pre_existing_disease_cover_3",
          display_name: "Covered after 3 years",
          description:
            "Pre-Existing ailment means any condition, injury or disease that is diagnosed or for which medical advice or treatment was recommended by, or received from, a physician prior to the effective date of the policy or its reinstatement. Medical Expesnes are covered after a waiting period of 3 years.\n                        ",
          operator: "equals",
          value_to_compare: "3 Years",
          visible_on_sections: ["health", "top_up"],
        },
        {
          code: "pre_existing_disease_cover_4",
          display_name: "Covered after 4 years",
          description:
            "Pre-Existing ailment means any condition, injury or disease that is diagnosed or for which medical advice or treatment was recommended by, or received from, a physician prior to the effective date of the policy or its reinstatement. Medical Expesnes are covered after a waiting period of 4 years.\n                        ",
          operator: "equals",
          value_to_compare: "4 Years",
          visible_on_sections: ["health", "top_up"],
        },
      ],
    },
    {
      group_name: "No Claim Bonus",
      code: "no_claim_bonus",
      type: "radio",
      options: [
        {
          code: "no_claim_bonus_50",
          display_name: "Upto 50%",
          description:
            "Increase or addition in the Sum Insured, maxium up to 50%  without any associated increase in premium in a claim free year.\n                        ",
          operator: "equals",
          value_to_compare: "Increase in Sum Insured maximum up to 50%",
          visible_on_sections: ["health"],
        },
        {
          code: "no_claim_bonus_100",
          display_name: "Upto 100%",
          description:
            "Increase or addition in the Sum Insured, maxium up to 100%  without any associated increase in premium in a claim free year.\n                        ",
          operator: "equals",
          value_to_compare: "Increase in Sum Insured maximum up to 100%",
          visible_on_sections: ["health"],
        },
        {
          code: "no_claim_bonus_150",
          display_name: "Upto 150%",
          description:
            "Increase or addition in the Sum Insured, maxium up to 150%  without any associated increase in premium in a claim free year.\n                        ",
          operator: "equals",
          value_to_compare: "Increase in Sum Insured maximum up to 150%",
          visible_on_sections: ["health"],
        },
        {
          code: "no_claim_bonus_200",
          display_name: "Upto 200%",
          description:
            "Increase or addition in the Sum Insured, maxium up to 200%  without any associated increase in premium in a claim free year.\n                        ",
          operator: "equals",
          value_to_compare: "Increase in Sum Insured maximum up to 200%",
          visible_on_sections: ["health"],
        },
      ],
    },
    {
      group_name: "Others",
      code: "others",
      type: "checkbox",
      options: [
        {
          code: "disease_wise_cover",
          display_name: "No limit on treatments",
          description:
            "No specific amount of claim amount is to be paid by the insured person for specific diseases/treatments/procedures.\n                        ",
          operator: "equals",
          value_to_compare: "No sub-limit",
          visible_on_sections: ["health"],
        },
        {
          code: "worldwide_coverage",
          display_name: "Worldwide Cover",
          description:
            "Worldwide coverage is a benefit that offers coverage all over the world.\n                        ",
          operator: "not_equals",
          value_to_compare: "Not Covered",
          visible_on_sections: ["health"],
        },
        {
          code: "free_health_check_up",
          display_name: "Free-health check up",
          description:
            "If You Renew Your Policy without a break, then at every Policy renewal Insurer will pay the expenses incurred towards cost of health check-up up to the Limits Per Policy (excluding any cumulative bonus) .\n                        ",
          operator: "equals",
          value_to_compare: "Yes",
          visible_on_sections: ["health"],
        },
        {
          code: "maternity_cover",
          display_name: "Maternity cover",
          description:
            "Maternity Cover Means Medical Expenses for a delivery (including complicated deliveries and caesarean sections) incurred during Hospitalization; The lawful medical  termination of pregnancy during the Policy Period;\n                        Pre-natal and post-natal Medical Expenses for delivery or termination.",
          operator: "not_equals",
          value_to_compare: "Not Covered",
          visible_on_sections: ["health", "top_up"],
        },
        {
          code: "no_claim_bonus_2",
          display_name: "No Claim Bonus",
          description:
            "No Claim Bonus means any increase or addition in the Sum Insured granted by the Insurer without any associated increase in premium in a claim free year.",
          operator: "equals",
          value_to_compare: "Not Covered",
          visible_on_sections: ["health", "top_up"],
        },
      ],
    },
  ],
  baseplantypes: [
    { code: "arogya_sanjeevani", display_name: "Arogya Sanjeevani" },
    { code: "global_plans", display_name: "Global Plans" },
    { code: "base_health", display_name: "Base health" },
    { code: "1_crore_plan", display_name: "1 crore plan" },
  ],
  defaultfilters: { cover: "300000-500000", tenure: "1", plan_type: "F" },
  settings: {
    journey_type: "cross_sell",
    mobile: "",
    email: "",
    license: "",
    logo: "",
    primary_color: "#0a87ff",
    secondary_color: "#2cd44a",
    primary_shade: "#ecf6ff",
    secondary_shade: "#eef1f4",
    addons_visibilty: "1",
    riders_visibilty: "1",
    footer: "",
    multiindividual_visibilty: "1",
    top_up_flow: ["Single_Top_Up_Journey"],
  },
  tenant: {
    id: 3,
    name: "Fyntune",
    alias: "fyntune",
    email: "health@gmail.com",
    term_frontend_domain:
      "termdemo-gbk1bfj4vz7bg2mxwhgvlaws2uebzxb4.fynity.in/",
    topup_frontend_domain:
      "https://topupdemo-gbk1bfj4vz7bg2mxwhgvlaws2uebzxb4.fynity.in",
  },
  deductibles,
};

export default config;
