export const members = [
  {
    code: "self",
    display_name: "Self",
    min_age: "18",
    max_age: "150",
    is_primary: true,
  },
  {
    code: "spouse",
    display_name: "Spouse",
    min_age: "18",
    max_age: "150",
    is_primary: true,
  },
  {
    code: "son",
    display_name: "Son",
    min_age: "0.3",
    max_age: "30",
    is_primary: true,
  },
  {
    code: "daughter",
    display_name: "Daughter",
    min_age: "0.3",
    max_age: "30",
    is_primary: true,
  },
  {
    code: "father",
    display_name: "Father",
    min_age: "40",
    max_age: "150",
    is_primary: true,
  },
  {
    code: "mother",
    display_name: "Mother",
    min_age: "40",
    max_age: "150",
    is_primary: true,
  },
  {
    code: "grand_father",
    display_name: "Grand Father",
    min_age: "54",
    max_age: "150",
    is_primary: false,
  },
  {
    code: "grand_mother",
    display_name: "Grand Mother",
    min_age: "54",
    max_age: "150",
    is_primary: false,
  },
  {
    code: "father_in_law",
    display_name: "Father-in-law",
    min_age: "40",
    max_age: "150",
    is_primary: false,
  },
  {
    code: "mother_in_law",
    display_name: "Mother-in-law",
    min_age: "40",
    max_age: "150",
    is_primary: false,
  },
];
